services:
  client:
    image: cc-client
    container_name: cc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped

  server:
    image: cc-server
    container_name: cc-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: cc-db
    volumes:
      - ./server/src/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    restart: unless-stopped
